name: Nuget Publish on Master Merged

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          10.x
          8.x
          6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Nuget Push
      run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGETORGKEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json
