name: Generate JSON SBOM

on:
  push:
    branches: ["sbom_carbon"]


jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - uses: CycloneDX/gh-dotnet-generate-sbom@master
        with:
          path: "**/*.csproj"
          json: true
          github-bearer-token: ${{ secrets.GITHUB_TOKEN }}
